name: very_good_example
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  bloc: ^8.1.4
  cached_network_image: ^3.4.0
  coffee_repository:
    path: packages/coffee_repository
  connectivity_plus: ^6.0.4
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  flutter_staggered_grid_view: ^0.7.0
  hydrated_bloc: ^9.1.5 
  intl: ^0.19.0
  oxidized: ^6.2.0
  path_provider: ^2.1.4
  shimmer: ^3.0.0

dev_dependencies:
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  path: ^1.9.0
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
