name: coffee_repository
description: A Dart Package to manage the Coffee Domain
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  coffee_api:
    path: ../coffee_api
  equatable: ^2.0.5
  oxidized: ^6.2.0

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.7
  very_good_analysis: ^6.0.0
